### ISSUE TITLE
add the comment

### ISSUE THREAD

**Issue by jhonsnow456** [jhonsnow456/Data-Structure-Algorithm#74]
https://github.com/jhonsnow456/Data-Structure-Algorithm/blob/31a46ecbe0fc54f0a046ab4981d21db6a1adebc5/DSA's%20Important/07_LinkedList/LinkedList.cpp#L218

**Comment by hey-amanthakur** [comment]
### ISSUE resolved https://github.com/jhonsnow456/Data-Structure-Algorithm/pull/75
